workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 10
    instance_type: linux_x2
    environment:
      groups:
        - keystore_credentials
        - aws_credentials
      vars:
        PACKAGE_NAME: io.nevercode.androidappcm
        # CM_KEYSTORE_PATH: /tmp/keystore.keystore
    triggering:
      events:
        - push
        # - pull_request
        # - tag
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Build Android app
        script: ./gradlew bundleRelease && ./gradlew assembleRelease
      - name: Update S3 bucket
        script: |
          echo $CM_BUILD_OUTPUT_DIR
          cd $CM_BUILD_OUTPUT_DIR
          ls
          aws s3 ls
          aws s3 sync $CM_BUILD_OUTPUT_DIR s3://cm-hpapp-builds/
          aws s3 sync /build_outputs/ s3://cm-hpapp-builds/
          aws s3 sync /clone/app/build/outputs/apk/release/
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    publishing:
      slack:
        channel: codemagic-builds-testing
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
