workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 10
    instance_type: linux_x2
    environment:
      groups:
        - keystore_credentials # <-- Includes - CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
      node: latest
    triggering:
      events:
        - push
      # branch_patterns:
      #   - pattern: release
      #     include: true
      #     source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Build Android app
        script: ./gradlew bundleRelease && ./gradlew assembleRelease # To generate an .apk use--> ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    # publishing:
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
