workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 10
    instance_type: linux_x2
    environment:
      groups:
        - keystore_credentials
        - aws_credentials
        - GOOGLE_APP_CREDENTIALS
      vars:
        PACKAGE_NAME: io.nevercode.androidappcm
        # CM_KEYSTORE_PATH: /tmp/keystore.keystore
    triggering:
      events:
        - push
        # - pull_request
        # - tag
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set up key.properties file for code signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      # - name: update s3 bucket
      #   script: |
      #     sudo pip3 install awscli --upgrade
      #     sudo pip install awscli --upgrade
      #     aws s3 sync $CM_BUILD_OUTPUT_DIR s3://cm-hpapp-builds/
      - name: Build Android app
        script: ./gradlew bundleRelease && ./gradlew assembleRelease
      - name: upload to Google storage
        script: |
          echo $GCLOUD_STORAGE_KEY > $CM_BUILD_DIR/gcloud_storage_key.json
          gcloud auth activate-service-account --key-file $CM_BUILD_DIR/gcloud_storage_key.json
          gsutil cp $CM_BUILD_DIR/app/build/outputs/**/*.apk gs://cmappbuilds
      - name: Update S3 bucket
        script: |
          echo $CM_BUILD_OUTPUT_DIR
          ls
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1
          aws s3 ls
          aws s3 sync $CM_BUILD_DIR/app/build/outputs/ s3://cm-hpapp-builds/
          aws s3 cp $CM_BUILD_DIR/app/build/outputs/**/*.apk s3://cm-hpapp-builds/
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    publishing:
      slack:
        channel: codemagic-builds-testing
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
